name: Deploy

on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NodeJS 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn
        working-directory: mcpbox

      - name: Build Application
        run: yarn build
        working-directory: mcpbox

      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --only functions --token $FIREBASE_TOKEN
        working-directory: mcpbox
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
